### ISSUE TITLE
Crear ejemplos de manipulación de los elementos del DOM

### ISSUE THREAD

**Issue by rvsweb** [RVSWeb/ProgramacionConJavascript#15]
Hay que realizar estos ejemplos básicos de este curso.
Aunque el manual no sea muy bueno. 👎 
[Miriadax](https://miriadax.net/documents/99348180/99348612/-Libreria+JQuery.pdf/b8d996e6-4667-4ad8-8d8d-76bdeb306a85?version=1.0)

**Comment by RVSWeb** [comment]
> Hay que realizar estos ejemplos básicos de este curso.
> Aunque el manual no sea muy bueno. 👎
> [Miriadax](https://miriadax.net/documents/99348180/99348612/-Libreria+JQuery.pdf/b8d996e6-4667-4ad8-8d8d-76bdeb306a85?version=1.0)

**Comment by rvsweb** [comment]
@rvs101 Esta tarea la tienes que realizar tu. 💪😄

**Comment by rvs101** [comment]
**Por supuesto** , Cuenta con ello :laughing:
